version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: mypassword
      POSTGRES_USER: myuser
      POSTGRES_DB: mydb
    ports:
      - 5432:5432
    networks:
      - mynetwork

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - mynetwork

  next-app2:
    build:
      context: .
      dockerfile: apps/wind-turbine-web/Dockerfile
    ports:
      - "3000:3000"
    networks:
      - mynetwork
    depends_on:
      - db
    command: /app/wait-for-it.sh db:5432 -- /bin/bash -c "npx prisma generate && npx prisma db push && npm run build && npm start"



  flask-app2:
    build:
      context: .
      dockerfile: apps/flask_app/Dockerfile
    ports:
      - "5000:5000"
    networks:
      - mynetwork
    depends_on:
      - db

networks:
  mynetwork:
    driver: bridge
